name: Code Quality Checks

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./server/

        steps:
            - uses: actions/checkout@v4
            - name: Use node 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  cache: 'yarn'
                  cache-dependency-path: './server/yarn.lock'
            - name: Install dependencies
              run: yarn
            - name: Run eslint checks
              run: yarn lint:check
            - name: Run test suite
              run: yarn test
              env:
                  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
